apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: npblkdsba-python 
  janus-idp.io/tekton: npblkdsba-python
  backstage.io/kubernetes-id: npblkdsba-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: npblkdsba-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml